name: Continuos integration with git hub actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - run: ./greadlew clean
      - run: ./gradlew testClasses
      - run: ./greadlew bootJar
